# Generated by Django 3.1 on 2021-05-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Sent', 'Sent'), ('Completed', 'Completed'), ('Cencelled', 'Cencelled')], default='New', max_length=11),
        ),
    ]
